services:
    frankenphp:
        env_file:
            -
                path: .env.prod
                required: false
        ports:
            - 80:80
            - 443:443
            - 443:443/udp

    phpmyadmin:
        ports:
            - 8080:8080
