services:
    frankenphp:
        container_name: ${COMPOSE_PROJECT_NAME}-frankenphp
        build:
            target: frankenphp_prod
        volumes:
            - caddy-config:/config
            - caddy-data:/data
        environment:
            SERVER_NAME: ${SERVER_NAME:-localhost}
        restart: unless-stopped

    db:
        container_name: ${COMPOSE_PROJECT_NAME}-db
        image: mariadb
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MARIADB_USER: ${MARIADB_USER:-app}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD:-!ChangeMe!}
            MARIADB_DATABASE: ${MARIADB_DATABASE:-app}
            MARIADB_RANDOM_ROOT_PASSWORD: true
        restart: unless-stopped

volumes:
    caddy-config:
    caddy-data:
    db-data:
